# Generated by Django 4.2.2 on 2023-06-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('author', models.CharField(blank=True, max_length=64)),
                ('location_type', models.PositiveSmallIntegerField()),
                ('location', models.TextField(blank=True)),
                ('instructions', models.TextField()),
                ('servings', models.CharField(blank=True, max_length=32)),
                ('prep_time', models.CharField(blank=True, max_length=32)),
                ('cook_time', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('personal_notes', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
